[project]
name = "cd2bel"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Adrien Rougny", email = "adrienrougny@gmail.com"},
]
dependencies = [
    "momapy @ git+https://github.com/adrienrougny/momapy.git@commute",
    "setuptools>=75.1.0",
    "pybel[neo4j]>=0.15.5",
    "pandas==2.2.2",
]
requires-python = "<=3.11,>=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "-e file:///home/rougny/code/ebel#egg=ebel",
]
